server:
  port: 9085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///hm49
    username: root
    password: admin
  redis:
    host: 192.168.153.129
  rabbitmq:
    host: 192.168.153.129
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo