server:
  port: 9086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.153.129
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
#自己去阿里云短信申请账号填一下这里就行了
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName:  # 签名名称
    verifyCodeTemplate:  # 模板名称